version: '3'
services: 
    web:
        build: .
        command: python3 app.py
        ports:
            - 5000:5000
        volumes:
            - ./app/work:/work
            - ./app:/app
        working_dir: /app