version: '3'
services:
  jphacks2021:
    image: node:16-slim
    volumes:
      - ".:/workspace:cached"
    command: /bin/bash -c "cd /workspace/doradora && yarn"
    tty: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002