version: '3'
services:
  jphacks2021:
    build: .
    volumes:
      - ".:/workspace:cached"
    command: yarn start
    env_file:
      - .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002